### ISSUE TITLE
clang_metashell: fatal error: unknown argument: '-profiler'

### ISSUE THREAD

**Issue by wbs0829** [sabel83/metashell#38] opened 2015-11-01 07:05 UTC
I compile metashell in archlinux with `cmake .. -DCMAKE_CXX_FLAGS:STRING="-Werror -DMETASHELL_DISABLE_TEMPLIGHT_TESTS" -DCLANG_STATIC=false -DCLANG_DEBUG=true -DCLANG_LIBRARYDIR=/lib/clang/3.7.0/lib -DNO_TEMPLIGHT=true` like https://travis-ci.org/sabel83/metashell/builds/87318313 .
Then `make metashell` and run it. After
```
#include <vector>
#msh mdb std::vector<int>
```
I get `clang_metashell: fatal error: unknown argument: '-profiler'`.
Both gcc and clang.

**Comment by wbs0829** [comment] 2015-11-01 07:11
Both gcc and clang.

**Comment by r0mai** [comment] 2015-11-01 10:07
Your clang needs to be compiled with [templight](https://github.com/mikael-s-persson/templight), to make mdb work.

I recommend using the clang which is bundled with metashell This version is compiled with templight. Follow the instructions here: http://metashell.readthedocs.org/en/stable/getting_metashell/build/

Let us know if you run into any problems.

**Comment by wbs0829** [comment] 2015-11-01 14:58
I use `./build.sh` to build metashell with gcc.
A link error:
```
...
Scanning dependencies of target metashell_unit_test
[ 69%] Building CXX object test/unit/CMakeFiles/metashell_unit_test.dir/mock_cxtranslationunit.cpp.o
[ 70%] Linking CXX executable metashell
[ 70%] Building CXX object test/unit/CMakeFiles/metashell_unit_test.dir/test_pragma_handler_map.cpp.o
[ 71%] Building CXX object test/unit/CMakeFiles/metashell_unit_test.dir/mock_console.cpp.o
[ 72%] Linking CXX static library libmetashell_system_test_lib.a
/usr/bin/ld: ../../3rd/templight/build/lib/libLLVMSupport.a(Process.cpp.o): undefined reference to symbol 'tigetnum'
/usr/lib/libncursesw.so.6: error adding symbols: DSO missing from command line
collect2: 错误：ld 返回 1
app/CMakeFiles/metashell.dir/build.make:323: recipe for target 'app/metashell' failed
make[2]: *** [app/metashell] Error 1
CMakeFiles/Makefile2:123: recipe for target 'app/CMakeFiles/metashell.dir/all' failed
make[1]: *** [app/CMakeFiles/metashell.dir/all] Error 2
...
```

**Comment by r0mai** [comment] 2015-11-01 15:03
What's the version of your compiler, and what operating system are you using?

**Comment by wbs0829** [comment] 2015-11-02 05:44
I try both gcc and clang. There is the same error.
```
$ uname -a
Linux amber-arch 4.2.5-1-ARCH #1 SMP PREEMPT Tue Oct 27 08:13:28 CET 2015 x86_64 GNU/Linux
$ gcc --version
gcc (GCC) 5.2.0
Copyright © 2015 Free Software Foundation, Inc.
本程序是自由软件；请参看源代码的版权声明。本软件没有任何担保；
包括没有适销性和某一专用目的下的适用性担保。
$ clang --version
clang version 3.7.0 (tags/RELEASE_370/final)
Target: x86_64-unknown-linux-gnu
Thread model: posix
```

**Comment by r0mai** [comment] 2015-11-06 12:44
I'll try to reproduce this error when I have some time.

After quick google search it might be that our llvm/clang is not linked together properly on your system.
http://stackoverflow.com/questions/21477407/llvm-3-5-fails-to-link
Although this SO post is quite old, so it might totally unrelated.

Again, I'll try to get back to you as soon as possible. If you have any success compiling, a PR with the fix would be greatly appreciated.

**Comment by r0mai** [comment] 2015-11-14 10:01
A fix (#39) has been merged to the develop branch. Please try it out and let us know if it works for you.

And thanks again for the report!

**Comment by wbs0829** [comment] 2015-11-16 02:56
It works!
Thank you!

**Closed** 2015-11-17 19:31 UTC

**Comment by dscole** [comment] 2017-06-19 16:59
I'm getting the same error, using a `brew install metashell` on macOS Sierra. Any idea what's going on?

**Comment by r0mai** [comment] 2017-06-19 17:03
@dscole can you post the entire error message and logs?

**Comment by dscole** [comment] 2017-06-19 17:17
```
> metashell --log metashell.log
/*
 * Template metaprogramming shell 3.0.0
 *
 * Metashell Copyright (C) 2015 Abel Sinkovics (abel@sinkovics.hu)
 *                              Andras Kucsma  (andras.kucsma@gmail.com)
 * This program comes with ABSOLUTELY NO WARRANTY. This is free software, and you are welcome to redistribute it under certain conditions; for details visit <http://www.gnu.org/licenses/>.
 *
 * Based on
 *   Boost.Wave 2.3.2.5406 [Mac OS/Clang version 8.0.0 (clang-800.0.38)]
 *   Readline   4.2
 *
 * Using precompiled headers
 * Maximum template depth: 1
 *
 * Getting help: #msh help
 */

> #msh mdb -
For help, type "help".
clang: fatal error: unknown argument: '-profiler'

(mdb) ^D
> ^D
```

```
> cat metashell.log
Start logging
Running shell
Searching Clang binary
Path of Clang shipped with Metashell: /templight_metashell
Clang binary shipped with Metashell is missing. Searching for another Clang binary at the following locations: , /usr/bin/clang++, /usr/local/bin/clang++, c:\Program Files (x86)\LLVM\bin\clang++.exe, c:\Program Files\LLVM\bin\clang++.exe
Clang binary found: /usr/bin/clang++
Determining include path of Clang: /usr/bin/clang++
Include path determined: ../include/metashell/libcxx;../include/metashell/templight
Generating percompiled header for /tmp/just-jjpToR/shell/metashell_environment.hpp
Running Clang: /usr/bin/clang++ -iquote . -x c++-header -I /tmp/just-jjpToR/shell -Wfatal-errors -std=c++0x -ftemplate-depth=256 -I../include/metashell/libcxx -I../include/metashell/templight -iquote . -w -o /tmp/just-jjpToR/shell/metashell_environment.hpp.pch /tmp/just-jjpToR/shell/metashell_environment.hpp
Clang's exit code: 0
Clang's stdout:
Clang's stderr:
Generating percompiled header for /tmp/just-jjpToR/shell/metashell_environment.hpp
Running Clang: /usr/bin/clang++ -iquote . -x c++-header -I /tmp/just-jjpToR/shell -Wfatal-errors -std=c++0x -ftemplate-depth=256 -I../include/metashell/libcxx -I../include/metashell/templight -iquote . -w -o /tmp/just-jjpToR/shell/metashell_environment.hpp.pch /tmp/just-jjpToR/shell/metashell_environment.hpp
Clang's exit code: 0
Clang's stdout:
Clang's stderr:
Starting input loop
Running Clang: /usr/bin/clang++ -iquote . -x c++-header -I /tmp/just-jjpToR/shell -Wfatal-errors -std=c++0x -ftemplate-depth=256 -I../include/metashell/libcxx -I../include/metashell/templight -Xclang -ast-dump -Xtemplight -profiler -Xtemplight -safe-mode -o /tmp/just-jjpToR/mdb/templight.pb -
Clang's exit code: 1
Clang's stdout:
Clang's stderr: clang: fatal error: unknown argument: '-profiler'

Generating percompiled header for /tmp/just-jjpToR/shell/metashell_environment.hpp
Running Clang: /usr/bin/clang++ -iquote . -x c++-header -I /tmp/just-jjpToR/shell -Wfatal-errors -std=c++0x -ftemplate-depth=256 -I../include/metashell/libcxx -I../include/metashell/templight -iquote . -w -o /tmp/just-jjpToR/shell/metashell_environment.hpp.pch /tmp/just-jjpToR/shell/metashell_environment.hpp
Clang's exit code: 0
Clang's stdout:
Clang's stderr:
Generating percompiled header for /tmp/just-jjpToR/shell/metashell_environment.hpp
Running Clang: /usr/bin/clang++ -iquote . -x c++-header -I /tmp/just-jjpToR/shell -Wfatal-errors -std=c++0x -ftemplate-depth=256 -I../include/metashell/libcxx -I../include/metashell/templight -iquote . -w -o /tmp/just-jjpToR/shell/metashell_environment.hpp.pch /tmp/just-jjpToR/shell/metashell_environment.hpp
Clang's exit code: 0
Clang's stdout:
Clang's stderr:
Input loop finished
```

**Comment by r0mai** [comment] 2017-06-19 17:20
The clang executable metashell found was not built with templight. Was there any error while running brew?

**Comment by dscole** [comment] 2017-06-19 17:25
No, I can't see anything wrong with the brew install (I'm a newbie with brew though):

```
> brew uninstall metashell
Uninstalling /usr/local/Cellar/metashell/3.0.0... (232 files, 52.4MB)
> brew install metashell
==> Downloading https://homebrew.bintray.com/bottles/metashell-3.0.0.sierra.bottle.tar.gz
Already downloaded: /Users/dcole/Library/Caches/Homebrew/metashell-3.0.0.sierra.bottle.tar.gz
==> Pouring metashell-3.0.0.sierra.bottle.tar.gz
==> Using the sandbox
�  /usr/local/Cellar/metashell/3.0.0: 232 files, 52.4MB
> 
```

**Comment by r0mai** [comment] 2017-06-19 17:27
I see. I don't have a Sierra machine at hand now, but I'll try to take a look at it later. Maybe the Sierra bottle was mis-built.

In the meantime you could try to compile it from source using `./build.sh`: http://metashell.org/getting_metashell/build/index.html#building-metashell-on-os-x

**Comment by dscole** [comment] 2017-06-19 17:31
I actually also have an ubuntu 16.10 machine, so for now I'm using the .deb you provide for ubuntu 16.04 and that seems to be working properly for me.

**Comment by dscole** [comment] 2017-06-19 17:34
BTW, sorry if it's a bit off topic, but stuff like this (I have other more minor "how do I do this questions") might be easier to communicate on gitter. Have you guys considered having a chatroom for metashell?

**Comment by r0mai** [comment] 2017-06-20 10:38
@dscole I opened a separate issue for this https://github.com/metashell/metashell/issues/163.
Fix is on the way (https://github.com/metashell/metashell/pull/164), but the Homebrew version won't get updated for a while (we need to do a complete release, which is a considerable effort).

As a workaround, you can still use the current Homebrew version by invoking metashell like this:

```bash
$(readlink -f $(which metashell))
```

Thanks for the report.

**Comment by dscole** [comment] 2017-06-20 13:11
Thanks a lot!

**Comment by r0mai** [comment] 2017-06-20 23:36
@dscole Oh, and about your question on where to ask questions about metashell, there are a few links here: http://metashell.org/about/community/index.html

In particular, there is a google group you can join and post to:
https://groups.google.com/forum/#!forum/metashell_discuss
